from setuptools import setup, find_packages

setup(
    name="quality_engineering_agentic_framework",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "openai>=1.0.0",
        "google-generativeai>=0.3.0",
        "pyyaml>=6.0",
        "selenium>=4.10.0",
        "webdriver-manager>=4.0.0",
        "pytest>=7.0.0",
        "click>=8.0.0",
        "pandas>=2.0.0",
        "streamlit>=1.22.0",
        "fastapi>=0.95.0",
        "uvicorn>=0.22.0",
        "python-dotenv>=1.0.0",
        "pydantic>=2.0.0",
        "pygments>=2.15.0",
        "python-multipart>=0.0.6",
        "httpx>=0.28.1",
        "nest-asyncio",
        "openpyxl",
        "beautifulsoup4>=4.12.2",
        "lxml>=4.9.2",
        "langchain>=0.1.0",
        "langchain-community>=0.0.10",
        "langchain-openai>=0.0.5",
        "chromadb>=0.4.0",
        "pypdf>=4.0.0",
        "tiktoken>=0.5.0",
        "docx2txt",
        "fpdf2",
        "python-docx",
    ],
    entry_points={
        "console_scripts": [
            "qeaf=quality_engineering_agentic_framework.cli.cli:main",
        ],
    },
    author="Your Name",
    author_email="your.email@example.com",
    description="Quality Engineering Agentic Framework for automated test generation using LLMs",
    keywords="testing, automation, llm, ai, agents",
    python_requires=">=3.8",
)